"""Real uploads to a dev bot: the one path fakes cannot vouch for.

``tests/test_telegram_sender.py`` proves the sender calls Pyrogram correctly. It
cannot prove Telegram *accepts* the result — that the caption HTML parses, that a
vertical video arrives vertical instead of squashed, that a stored ``file_id``
really resends, that an album chunks. Those only fail against the live API, and
they are exactly the failures users see.

Opt-in twice over (marker + ``RUN_TELEGRAM_TESTS=1``) and it needs a **dev** bot,
never the production one: uploads land in a real chat.

    TG_TEST_BOT_TOKEN=<dev bot token>   # from BotFather, NOT TG_BOT_API
    TG_TEST_CHAT_ID=<your user id>      # press Start on the dev bot first —
                                        # a bot cannot open a conversation
    RUN_TELEGRAM_TESTS=1 ./venv/bin/pytest -q -m telegram

Messages are left in the chat on purpose: seeing them is half the point. Set
``TG_TEST_CLEANUP=1`` to have each test delete what it sent.

Media is generated by ffmpeg at run time rather than committed, so the repo keeps
no binary fixtures and the dimensions under test are stated in the test itself.
"""

import os
import subprocess
from types import SimpleNamespace

import aiosqlite
import pytest
import pytest_asyncio
from pyrogram.client import Client
from pyrogram.enums import MessageEntityType
from pyrogram.errors import FloodWait

import live_env
import live_links
from src.bot.orchestrator import DownloadOrchestrator
from src.config import Config
from src.core.models import MediaItem, Post, PostMeta
from src.platforms.instagram import InstagramPlatform
from src.platforms.youtube import YouTubePlatform
from src.services.sender import TelegramSender
from src.services.video import VideoProcessor
from src.storage.database import Database
from src.utils.captions import build_caption
from src.utils.urls import clean_url

pytestmark = [
    pytest.mark.telegram,
    pytest.mark.skipif(
        os.getenv("RUN_TELEGRAM_TESTS") != "1",
        reason="live upload test: set RUN_TELEGRAM_TESTS=1 to run it",
    ),
    # One event loop for the whole module so the bot below can be authorized once.
    pytest.mark.asyncio(loop_scope="session"),
]

_TOKEN = os.getenv("TG_TEST_BOT_TOKEN", "")
_CHAT_ID = os.getenv("TG_TEST_CHAT_ID", "")



# --- media fixtures ----------------------------------------------------------

def _make_video(path, width, height, seconds=3):
    """A tiny H.264/AAC clip of exactly the given size, via ffmpeg."""
    subprocess.run(
        [
            "ffmpeg", "-y",
            "-f", "lavfi", "-i", f"testsrc2=size={width}x{height}:rate=25:duration={seconds}",
            "-f", "lavfi", "-i", f"sine=frequency=440:duration={seconds}",
            "-c:v", "libx264", "-preset", "veryfast", "-pix_fmt", "yuv420p",
            "-c:a", "aac", "-b:a", "64k", "-movflags", "+faststart",
            "-shortest", str(path),
        ],
        check=True, capture_output=True,
    )
    return str(path)


def _make_image(path, width=800, height=600):
    subprocess.run(
        [
            "ffmpeg", "-y",
            "-f", "lavfi", "-i", f"testsrc2=size={width}x{height}:duration=1",
            "-frames:v", "1", str(path),
        ],
        check=True, capture_output=True,
    )
    return str(path)


# --- test doubles ------------------------------------------------------------

class RecordingClient:
    """The real Pyrogram client, keeping every Message the sender produced.

    ``send_post`` only hands back a file_id, but these tests need Telegram's own
    view of what arrived — dimensions, caption entities — so the Messages are
    captured out here instead of by widening the production return type.
    """

    def __init__(self, client):
        self._client = client
        self.videos = []
        self.photos = []
        self.groups = []
        # A fresh upload passes a local path; a cached resend passes a file_id
        # string. Keeping the kwargs is the only way to tell those apart.
        self.video_kwargs = []

    def __getattr__(self, name):
        return getattr(self._client, name)

    async def send_video(self, **kwargs):
        self.video_kwargs.append(kwargs)
        message = await self._client.send_video(**kwargs)
        self.videos.append(message)
        return message

    async def send_photo(self, **kwargs):
        message = await self._client.send_photo(**kwargs)
        self.photos.append(message)
        return message

    async def send_media_group(self, **kwargs):
        messages = await self._client.send_media_group(**kwargs)
        self.groups.append(messages)
        return messages

    @property
    def all_messages(self):
        return [*self.videos, *self.photos, *(m for g in self.groups for m in g)]

    async def cleanup(self):
        by_chat = {}
        for message in self.all_messages:
            by_chat.setdefault(message.chat.id, []).append(message.id)
        for chat_id, ids in by_chat.items():
            try:
                await self._client.delete_messages(chat_id, ids)
            except Exception as e:  # a bot may only delete its own, and only for 48h
                print(f"cleanup skipped for {chat_id}: {e}")


class StatusRecorder:
    """Stands in for StatusReporter, keeping the progress text for assertions."""

    def __init__(self):
        self.texts = []
        self.done_called = False

    async def set(self, text):
        self.texts.append(text)

    async def done(self):
        self.done_called = True


class Incoming:
    """Stands in for the user's message.

    ``reply_text`` returns a *real* Telegram message, so StatusReporter's edits and
    final delete are exercised for real too.
    """

    def __init__(self, bot, chat_id):
        self._bot = bot
        self.chat = SimpleNamespace(id=chat_id)
        self.from_user = SimpleNamespace(id=chat_id)
        self.status = None

    async def reply_text(self, text):
        self.status = await self._bot.send_message(self.chat.id, text)
        return self.status


# --- fixtures ----------------------------------------------------------------

@pytest.fixture
def chat_id():
    if not _CHAT_ID.lstrip("-").isdigit():
        pytest.skip("set TG_TEST_CHAT_ID to the chat the dev bot should post to")
    return int(_CHAT_ID)


@pytest_asyncio.fixture(scope="session", loop_scope="session")
async def bot():
    """One authorized client for the whole run.

    Deliberately session-scoped *and* backed by a session file on disk: Telegram
    rate-limits bot authorization hard (a per-test login earned a FLOOD_WAIT of
    3169s), so this signs in once and every later run resumes from
    ``data/ytdl_test_bot.session`` without signing in at all.
    """
    if not _TOKEN:
        pytest.skip("set TG_TEST_BOT_TOKEN to a dev bot token (never TG_BOT_API)")
    if not (Config.API_ID and Config.API_HASH):
        pytest.skip("MTProto needs TG_APP_ID and TG_API_HASH, same as the real bot")
    if _TOKEN == Config.BOT_TOKEN:
        pytest.fail("TG_TEST_BOT_TOKEN is the production token; use a separate dev bot")

    os.makedirs(Config.DATA_DIR, exist_ok=True)
    app = Client(
        "ytdl_test_bot", api_id=Config.API_ID, api_hash=Config.API_HASH,
        bot_token=_TOKEN, workdir=Config.DATA_DIR,
    )
    try:
        await app.start()
    except FloodWait as e:
        # Rate limiting is an environment condition, not a code failure: skip with
        # the wait so the tier reports a reason instead of a wall of errors.
        pytest.skip(f"Telegram is rate-limiting this bot's login: retry in {e.value}s")
    try:
        yield app
    finally:
        await app.stop()


@pytest_asyncio.fixture(loop_scope="session")
async def client(bot):
    recorder = RecordingClient(bot)
    yield recorder
    if os.getenv("TG_TEST_CLEANUP") == "1":
        await recorder.cleanup()


@pytest.fixture
def landscape(tmp_path):
    live_env.skip_unless_ffmpeg()
    return _make_video(tmp_path / "landscape.mp4", 1280, 720)


@pytest.fixture
def portrait(tmp_path):
    live_env.skip_unless_ffmpeg()
    return _make_video(tmp_path / "portrait.mp4", 720, 1280)


# The dev chat is meant to be read by a human afterwards, so each message says
# which case produced it. The link points at the repo rather than a real video:
# the media here is a synthetic ffmpeg pattern, and a caption pointing at some
# unrelated YouTube clip reads as "the bot sent the wrong video".
_REPO_URL = "https://github.com/sviperm/ytdl-tgbot"


def _post(media, title, url=_REPO_URL, duration=3, width=1280, height=720):
    return Post(
        meta=PostMeta(
            video_id="test", platform="test", title=title,
            caption_html=build_caption(title, url),
            duration=duration, width=width, height=height, supports_cache=True,
        ),
        media=media,
    )


# --- single video ------------------------------------------------------------

async def test_single_video_uploads_and_returns_reusable_file_id(client, chat_id, landscape):
    thumb = await VideoProcessor().make_thumbnail(landscape)
    post = _post([MediaItem("video", landscape, thumb)],
                 title="[test] single video 1280x720 + thumbnail")
    status = StatusRecorder()

    result = await TelegramSender().send_post(client, chat_id, post, status)

    assert result.file_id, "no file_id came back, so nothing could ever be cached"
    message = client.videos[-1]
    assert message.video is not None, "Telegram filed it as something other than a video"
    # The dimensions the bot declares are what Telegram plays it back at; a wrong
    # pair is the difference between a video and a letterboxed sliver.
    assert (message.video.width, message.video.height) == (1280, 720)
    assert message.video.duration == 3
    assert message.video.thumbs, "no thumbnail survived the upload"
    # The upload progress bar is a product requirement, not decoration.
    assert any("Uploading" in text and "MB" in text for text in status.texts), \
        f"no upload progress was reported, only: {status.texts}"


async def test_vertical_video_arrives_vertical(client, chat_id, portrait):
    post = _post([MediaItem("video", portrait)],
                 title="[test] vertical video 720x1280", width=720, height=1280)

    await TelegramSender().send_post(client, chat_id, post, StatusRecorder())

    video = client.videos[-1].video
    assert video.height > video.width, \
        f"shorts must stay portrait, Telegram reports {video.width}x{video.height}"


async def test_caption_html_parses_and_links_to_the_cleaned_source(client, chat_id, landscape):
    # Characters that would break a naive caption builder, plus a tracking param
    # that must not reach the link Telegram shows.
    title = '[test] caption escaping: & <angle> "quoted"'
    shared = "https://youtu.be/aqz-KE-bpKQ?si=lIrGXWyKMLmMbtGz"
    post = _post([MediaItem("video", landscape)], title=title, url=shared)

    await TelegramSender().send_post(client, chat_id, post, StatusRecorder())

    message = client.videos[-1]
    # Telegram hands the text back decoded, so this proves the escaping round-trips
    # instead of leaking &amp; into what the user reads.
    assert message.caption == title
    links = [e for e in (message.caption_entities or [])
             if e.type == MessageEntityType.TEXT_LINK]
    assert len(links) == 1, f"expected one source link, got {message.caption_entities}"
    assert links[0].url == clean_url(shared)


async def test_stored_file_id_resends_without_the_file(client, chat_id, landscape):
    """The cache path: a second request must resend from the id alone."""
    post = _post([MediaItem("video", landscape)],
                 title="[test] cached resend by file_id")
    result = await TelegramSender().send_post(client, chat_id, post, StatusRecorder())
    assert result.file_id

    os.remove(landscape)  # prove nothing local is read on the cached path
    await TelegramSender().send_cached_video(client, chat_id, result.file_id, post.meta)

    resent = client.videos[-1]
    assert resent.video is not None
    assert (resent.video.width, resent.video.height) == (1280, 720)
    assert resent.caption == post.meta.title


# --- photos and albums -------------------------------------------------------

async def test_single_photo_uploads_without_a_file_id(client, chat_id, tmp_path):
    live_env.skip_unless_ffmpeg()
    image = _make_image(tmp_path / "single.jpg")
    post = _post([MediaItem("image", image)], title="[test] single photo")

    result = await TelegramSender().send_post(client, chat_id, post, StatusRecorder())

    assert result.file_id is None, "only videos are cacheable"
    assert client.photos[-1].photo is not None


async def test_mixed_album_captions_only_the_first_item(client, chat_id, tmp_path, landscape):
    """The Instagram carousel shape: one video plus photos, one caption."""
    live_env.skip_unless_ffmpeg()
    images = [_make_image(tmp_path / f"carousel_{i}.jpg") for i in range(2)]
    post = _post(
        [
            MediaItem("video", landscape, await VideoProcessor().make_thumbnail(landscape)),
            MediaItem("image", images[0]),
            MediaItem("image", images[1]),
        ],
        title="[test] album: 1 video + 2 photos, caption on the first only",
    )

    await TelegramSender().send_post(client, chat_id, post, StatusRecorder())

    assert len(client.groups) == 1, "a 3-item post must go as one album"
    album = client.groups[0]
    assert len(album) == 3
    assert album[0].caption == post.meta.title
    # Telegram shows an album's caption from its first item; captions on the rest
    # would render as stray text under the photos.
    assert all(not m.caption for m in album[1:])


async def test_album_beyond_ten_items_is_chunked(client, chat_id, tmp_path):
    live_env.skip_unless_ffmpeg()
    images = [_make_image(tmp_path / f"bulk_{i}.jpg", 320, 240) for i in range(12)]
    post = _post([MediaItem("image", path) for path in images],
                 title="[test] album chunking: 12 photos -> 10 + 2")

    await TelegramSender().send_post(client, chat_id, post, StatusRecorder())

    # Telegram rejects an album larger than 10, so 12 must arrive as 10 + 2.
    assert [len(group) for group in client.groups] == [10, 2]
    assert client.groups[0][0].caption == post.meta.title


# --- the whole pipeline ------------------------------------------------------

async def _cache_rows(db):
    """Every (platform, video_id) the run cached; Database exposes no listing."""
    async with aiosqlite.connect(db.db_path) as conn:
        async with conn.execute("SELECT platform, video_id FROM videos") as cursor:
            return await cursor.fetchall()


def _entry(name):
    """One row from the shared link table, by name."""
    return next(e for e in live_links.URLS if e.name == name)


def _album_kinds(messages):
    """Map an album back to the media vocabulary the table uses."""
    return ["video" if m.video else "image" for m in messages]


@pytest.mark.network
@pytest.mark.parametrize("entry", live_links.E2E, ids=live_links.ids(live_links.E2E))
async def test_pipeline_end_to_end(entry, client, chat_id, bot, tmp_path, monkeypatch):
    """Every service, all the way through: probe, download, process, send, cache.

    The other tests here hand the sender a file that was never downloaded, so they
    cannot catch a platform whose own fetch path is broken — and Instagram's is the
    most fragile of them (no login, a third-party fixer, an offload host that moves).
    Runs against the **production** registry so the wiring and resolution order in
    src/container.py are what gets exercised.
    """
    if entry.platform is YouTubePlatform:
        live_env.skip_unless_youtube_env_ready()
    if entry.platform is InstagramPlatform and not live_env.tcp_reachable(
        Config.IG_FIXER_URL, timeout=10
    ):
        pytest.skip(f"Instagram fixer host {Config.IG_FIXER_URL} is unreachable")

    downloads = tmp_path / "downloads"
    downloads.mkdir()
    monkeypatch.setattr(Config, "DOWNLOAD_DIR", str(downloads))

    from src.container import container  # lazy: keeps collection independent of it

    db = Database(str(tmp_path / "dev_cache.db"))
    await db.initialize()
    orchestrator = DownloadOrchestrator(
        container.registry, TelegramSender(), db, max_concurrent=1,
    )

    await orchestrator.handle_url(client, Incoming(bot, chat_id), entry.url)

    if entry.sends_as == "album":
        assert client.groups, "nothing reached Telegram; check the dev chat's status message"
        album = client.groups[-1]
        # A carousel that silently loses items is the Instagram failure mode.
        assert _album_kinds(album) == list(entry.media_types)
        assert album[0].caption, "an album must carry the post caption on its first item"
    elif entry.sends_as == "image":
        assert client.photos, "no photo reached Telegram"
        assert client.photos[-1].photo is not None
    else:
        assert client.videos, "no video reached Telegram"
        video = client.videos[-1].video
        assert video is not None, "Telegram filed it as something other than a video"
        assert video.duration > 0, "a video sent with duration 0 has no seek bar"
        # Dimensions must survive the whole pipeline, not just probe(): sent as 0
        # Telegram renders a vertical clip as a squashed strip.
        if entry.orientation == "portrait":
            assert video.height > video.width, \
                f"{entry.name} must stay portrait, Telegram reports {video.width}x{video.height}"
        elif entry.orientation == "landscape":
            assert video.width > video.height, \
                f"{entry.name} must stay landscape, Telegram reports {video.width}x{video.height}"

    # handle_url turns its own failures into a status message, so the cache row is
    # what proves the run completed rather than reporting an error to the user.
    rows = await _cache_rows(db)
    assert len(rows) == (1 if entry.expects_cache_row else 0), \
        f"expected {'one' if entry.expects_cache_row else 'no'} cache row, got {rows}"
    assert os.listdir(downloads) == [], "the per-request work dir was not cleaned up"


@pytest.mark.network
async def test_second_request_is_served_from_cache(client, chat_id, bot, tmp_path, monkeypatch):
    """The same link twice: download once, then resend from the stored file_id.

    Every other e2e case gets a *fresh* dev database precisely so a leftover
    file_id can never short-circuit the download it is meant to exercise. This one
    is the opposite: it keeps one dev database across both runs, because skipping
    the download is the behaviour under test. Neither ever touches the production
    cache at data/bot_database.db.

    VK, because it needs no PO-token provider and the clip is 9 seconds.
    """
    entry = _entry("generic-vk-landscape")
    downloads = tmp_path / "downloads"
    downloads.mkdir()
    monkeypatch.setattr(Config, "DOWNLOAD_DIR", str(downloads))

    from src.container import container

    db = Database(str(tmp_path / "dev_cache.db"))
    await db.initialize()
    orchestrator = DownloadOrchestrator(
        container.registry, TelegramSender(), db, max_concurrent=1,
    )

    await orchestrator.handle_url(client, Incoming(bot, chat_id), entry.url)
    rows = await _cache_rows(db)
    assert len(rows) == 1, f"first run cached nothing: {rows}"
    platform, video_id = rows[0]
    file_id = await db.get_file_id(platform, video_id)
    assert len(client.videos) == 1
    assert client.video_kwargs[0]["video"] != file_id, "first run must upload a real file"

    await orchestrator.handle_url(client, Incoming(bot, chat_id), entry.url)

    assert len(client.videos) == 2, "the cached request delivered nothing"
    # The proof it never re-downloaded: Telegram was handed the stored id, not a path.
    assert client.video_kwargs[1]["video"] == file_id
    assert await _cache_rows(db) == rows, "a cache hit must not add a row"
    assert os.listdir(downloads) == [], "work dirs were left behind"
